### ISSUE TITLE
Where is the actual bot logic?

### ISSUE THREAD

**Issue by Stan-Stani** [ROUNDS-Preservation/RoundWithBot#3]
I've looked through the code a few times and I can't figure out where the logic is for the bot movement and combat.

**Comment by AALUND13** [comment]
Bot movement and combat are built-in into the game the AI component called "PlayerAIPhilip" There are multiple AI types like "PlayerAi" but I use "PlayerAIPhilip" because that is the best AI built-in the game.

If you want to ask more questions feel free to ask in new issues.
