### ISSUE TITLE
Mouse cursor rising

### ISSUE THREAD

**Issue by LORDP1ZZAMAN** [ROUNDS-Preservation/RoundWithBot#4]
my game and more importantly, my mouse cursor, work fine until i add a bot to the lobby. from the moment i add the bot my cursor will rise uncontrollably until i either leave the match or close the game which immediately fixes it.

**Comment by LORDP1ZZAMAN** [comment]
further update, when the actual match starts the cursor will move to random spots completely on its own. i'm pretty sure the AI is hijacking my cursor and moving it wherever they are aiming

**Comment by AALUND13** [comment]
I can't reproduce the bug that the mouse is being hijacked by bots could you send your logs when the glitch happens thank you.

And also turn on Debugging mode in the mod Config Settings.

You can find and upload your debug log by going to Settings -> Locations -> Browse Profile Folder -> (in the new window that opens up) Bepinex folder -> Upload the LogOutput.log file.

**Comment by LORDP1ZZAMAN** [comment]
i went back to try again before doing this to make sure that it hadn't changed and it worked perfectly fine. i looked at file and from i can tell the issue was that something simply hadn't updated properly when i updated my modpack and was causing issues but it seems like it ironed itself out now.
