### ISSUE TITLE
Broken visuals... From the start.

### ISSUE THREAD

**Issue by AMatt0** [ROUNDS-Preservation/RoundWithBot#6]
You may want to fix this issue... Its a bit unplayable. And by a bit, i mean it completely ruins the game (The visual glitch, i could still hear the bot working, so I'm sure you did a good job). So basicly, when i load up, It looks like... This. 

![image](https://github.com/ROUNDS-Preservation/RoundWithBot/assets/169317486/7641a8ca-a704-4d83-89ee-83f971de9756)

... Yeah... A Bit weird. But however, when i move over to the versus local, it becomes this.

![image](https://github.com/ROUNDS-Preservation/RoundWithBot/assets/169317486/a47be196-2dcc-4188-8231-728af325bc1c)

so yeah. I can hear the bot working, but the visuals are not. I hope you get this fixed!

-Signed, Matthew D

**Comment by Scyye** [comment]
Closing.
This has nothing to do with RoundsWithBot, downgrade your game.
