### ISSUE TITLE
the bot doesn't ready up 

### ISSUE THREAD

**Issue by iluhu** [ROUNDS-Preservation/RoundWithBot#7]
i press r like it says and it does nothing

**Comment by AALUND13** [comment]
Does it ready some bots and unready the other bots, or does it not ready any of them?

**Comment by iluhu** [comment]
doesnt ready any of them. maybe downgrade?

**Comment by AALUND13** [comment]
Yea, you have to downgrade your rounds to get any mods to work.

**Comment by iluhu** [comment]
oh ok thanks
